[tool.poetry]
name = "pythonisweird"
version = "0.1.0"
description = ""
authors = ["inomata137"]

packages = [
  { include = "pythonisweird" }
]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
